Repository amanjaiman1/Product_3D, pull requests merged in 2023-05, with the labels that each got.

#148 issue #146
  client/src/components/Navbar.jsx
  client/src/components/navbar.css
Labels: GSSOC'23, Level 2

#156 Balaji sivasakthi/fix team section
  client/src/components/ContributorCard/index.jsx
  client/src/components/Pagination/index.jsx
  client/src/containers/Contributors/index.jsx
  client/src/containers/Hero/index.jsx
  client/src/index.css
  client/tailwind.config.js
Labels: GSSOC'23, ⚒️ goal: fix, Level 1

#198 Added Questions
  client/src/pages/Faq/Faq.jsx
  client/src/pages/Faq/faq.css
Labels: GSSOC'23, Level 1

#200 resolved the navbar issues
  client/package-lock.json
  client/src/containers/Header/Navbar.jsx
  client/src/index.css
Labels: GSSOC'23, Level 2

#193 Frontend: added preloader page
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/assets/image/Favicon1.png
  client/src/assets/index.js
Labels: GSSOC'23, Level 3
