Repository amanjaiman1/Product_3D, pull requests merged in 2023-06, with the labels that each got.

#322 #320 Bot added
  .github/ISSUE_TEMPLATE/workflows/close_old_issues.yaml
Labels: gssoc23, ⭐ goal: addition, level2

#323 #319 depandabot added
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/dependabot.yml
Labels: gssoc23, level2

#341 Controlled Swipers Speed in Testimonial Section
  client/src/containers/TeamPost/TeamPostCard.jsx
Labels: gssoc23, level1

#353 Update README.md issue-357
  README.md
Labels: gssoc23, level1

#362 NavLogo
  client/src/assets/image/logo.png
  client/src/assets/index.js
  client/src/containers/Header/Navbar.jsx
Labels: gssoc23, level2

#369 [Feat] Customizer Model loader
  .commitlintrc.json
  client/package-lock.json
  client/package.json
  client/src/assets/lottie/95250-3d-loader.json
  client/src/components/CustomizerViewer/CameraRig.jsx
  client/src/components/CustomizerViewer/Shirt.jsx
  client/src/components/CustomizerViewer/index.jsx
  package-lock.json
Labels: gssoc23, 👨🏻‍🚒 goal: major, level3
