Repository amanjaiman1/Product_3D, pull requests merged in 2023-08, with the labels that each got.

#598 Made changes in About us Page
  src/assets/about/EC.jpg
  src/assets/about/character.webp
  src/assets/about/first.webp
  src/assets/about/join.webp
  src/assets/about/second.webp
  src/containers/Footer/index.js
  src/pages/About us/About.jsx
Labels: gssoc23, 🟧 priority: high, ⭐ goal: addition, ⚒️ goal: fix, level3

#595 feat: fixed design and search bar and add tags
  src/components/BlogCard/bcard.jsx
  src/pages/Blog/Blog.jsx
  src/views/app/Home/index.jsx
Labels: gssoc23, 🟥 priority: critical, ⭐ goal: addition, ⚒️ goal: fix, level3

#596 feat(blog): designed blog page
  src/assets/image/anime1.png
  src/assets/image/anime2.jpeg
  src/assets/image/anime3.png
  src/assets/index.js
  src/components/BlogCard/bcard.jsx
  src/index.css
  src/pages/Blog/Blog.jsx
  src/store/blogData.js
Labels: gssoc23, 🟧 priority: high, 👨🏻‍🚒 goal: major, level3

#602 [FEAT]: navbar designed and made responsiveness
  src/components/Button/index.jsx
  src/containers/Header/Navbar.jsx
  src/index.css
Labels: enhancement, gssoc23, level3

#610 Development to main
  src/assets/image/ambassador.png
  src/assets/image/news1.png
  src/assets/image/news2.png
  src/assets/image/news3.png
  src/assets/image/video1.png
  src/assets/image/video2.png
  src/assets/image/video3.png
  src/assets/index.js
  src/components/Ambassador/index.jsx
  src/components/CommunityNews/index.jsx
  src/components/CommunityVideos/index.jsx
  src/pages/CommunityLanding/index.jsx
  src/views/app/CommunityLanding/index.jsx
Labels: gssoc23, 🟥 priority: critical, level3

#612 feat(community): designed community news cards
  src/components/CommunityNews/index.jsx
  src/views/app/CommunityLanding/index.jsx
Labels: gssoc23, ⭐ goal: addition, level3

#622 feat: Update CONTRIBUTING.md ✨
  CONTRIBUTING.md
Labels: gssoc23, 🟧 priority: high, level2

#623 [FEAT]: FAQ feature in helpCenter
  public/animations/explorebg.jpg
  public/explorebg.jpg
  src/App.jsx
  src/assets/image/tshirt.gif
  src/assets/index.js
  src/components/Helpfaq/index.jsx
  src/views/app/Helpcentre/index.jsx
Labels: gssoc23, 🟥 priority: critical, level3

#631 feat(explore): implemented community feature
  src/components/ExploreCommunity/index.jsx
  src/views/app/Explore/index.jsx
Labels: gssoc23, 🟧 priority: high, ⭐ goal: addition, level3

#632 feat(explore): Added Our Design work feature
  src/components/ExploreCustomized/index.jsx
  src/views/app/Explore/index.jsx
Labels: gssoc23, 🟥 priority: critical, 👨🏻‍🚒 goal: major, level3

#637 feat(explore): implemented our work feature
  src/components/ExploreWork/index.jsx
  src/views/app/Explore/index.jsx
Labels: gssoc23, 🟥 priority: critical, ⭐ goal: addition, level3

#644 fix: footer design
  src/containers/Footer/index.jsx
  src/containers/HightLights/index.jsx
  src/layout/HomeLayout.jsx
Labels: gssoc23, 🟥 priority: critical, level3

#653 Fixed Responsiveness
  src/components/Helpfaq/index.jsx
  src/components/Needhelp/index.jsx
  src/pages/About us/About.jsx
  src/pages/Helpcenter/Helpcentre.jsx
Labels: gssoc23, 🟥 priority: critical, ⭐ goal: addition, ⚒️ goal: fix, level3

#655 fix: button style in customizer
  src/components/ContextMenu/index.jsx
  src/components/CustomizerNavBar/index.jsx
  src/components/CustomizerTopbar/index.jsx
  src/containers/ProfileContainer/index.jsx
  src/containers/SettingsContainer/index.jsx
Labels: gssoc23, 🟥 priority: critical, ⭐ goal: addition, level3

#657 feat(explore): Implemented Event Container
  src/assets/image/event1.png
  src/assets/image/event2.png
  src/assets/image/event3.png
  src/assets/index.js
  src/components/Ambassador/index.jsx
  src/components/CommunityNews/index.jsx
  src/components/CommunityVideos/index.jsx
  src/components/ExploreCommunity/index.jsx
  src/components/ExploreCustomized/index.jsx
  src/components/ExploreWork/index.jsx
  src/containers/ExploreEvent/index.jsx
  src/pages/CommunityLanding/index.jsx
  src/pages/Helpcenter/Helpcentre.jsx
  src/views/app/Explore/index.jsx
Labels: gssoc23, 🟥 priority: critical, 👨🏻‍🚒 goal: major, level3

#659 feat(community): implemented funding program
  src/containers/CommunityFunding/index.jsx
  src/views/app/CommunityLanding/index.jsx
Labels: gssoc23, 🟥 priority: critical, ⭐ goal: addition, 👨🏻‍🚒 goal: major, level3

#663 feat(community): Implemented funding features
  src/assets/image/avail.png
  src/assets/image/funding.png
  src/assets/image/money.png
  src/assets/index.js
  src/containers/FundingPurpose/index.jsx
  src/views/app/CommunityLanding/index.jsx
Labels: gssoc23, 🟥 priority: critical, ⚒️ goal: fix, 👨🏻‍🚒 goal: major, level3

#666 Feat: team design in customizer
  src/App.jsx
  src/components/CustomizerSidebar/index.jsx
  src/containers/TeamContainer/index.jsx
  src/views/app/Teams/index.jsx
Labels: gssoc23, 🟥 priority: critical, 👨🏻‍🚒 goal: major, level3

#668 feat: search functionality in teams
  src/containers/TeamContainer/index.jsx
Labels: gssoc23, 🟥 priority: critical, level3

#670 feat: search functionality on customizer plugin
  src/containers/PluginsContainer/index.jsx
Labels: gssoc23, 🟥 priority: critical, level3

#677 feat: set dark theme in customiser page
  src/components/Button/index.jsx
  src/components/CustomizerNavBar/index.jsx
  src/components/CustomizerSettings/index.jsx
  src/components/CustomizerSidebar/index.jsx
  src/components/CustomizerTabs/index.jsx
  src/components/CustomizerTitle/index.jsx
  src/components/CustomizerToolTip/index.jsx
  src/components/CustomizerTopbar/index.jsx
  src/components/DialogBox/index.jsx
  src/containers/Customizer/index.jsx
  src/layout/EditorHomeLayout.jsx
  src/layout/EditorLayout.jsx
  src/pages/Blog/CreatePost.jsx
Labels: gssoc23, 🟥 priority: critical, ⭐ goal: addition, level3

#679 feat: working of the next prev buttons in customiser page
  src/components/CustomizerLogo/index.jsx
Labels: gssoc23, 🟥 priority: critical, ⭐ goal: addition, level3

#672 feat: create team
  src/App.jsx
  src/containers/CreateTeamContainer/index.jsx
  src/containers/TeamContainer/index.jsx
  src/views/app/CreateTeam/index.jsx
Labels: gssoc23, 🟥 priority: critical, ⭐ goal: addition, 👨🏻‍🚒 goal: major, level3

#682 feat(ambassador): implemented ambassador page
  src/assets/image/gallery1.jpg
  src/assets/image/gallery2.jpg
  src/assets/image/gallery3.png
  src/assets/index.js
  src/containers/AmbassadorHero/index.jsx
  src/containers/EventGallery/index.jsx
  src/views/app/Explore/index.jsx
Labels: gssoc23, 🟥 priority: critical, 👨🏻‍🚒 goal: major, level3

#700 feat: team create firebase
  src/containers/CreateTeamContainer/index.jsx
Labels: gssoc23, ⭐ goal: addition, level3

#704 Fixed edit blog option
  src/components/BlogCard/bcard.jsx
  src/pages/Blog/Blog.jsx
  src/pages/Blog/CreatePost.jsx
Labels: gssoc23, 🟥 priority: critical, ⚒️ goal: fix, 👨🏻‍🚒 goal: major, level3

#706 fix: dark style
  src/components/FormGroup/index.jsx
  src/components/PluginCard/index.jsx
  src/components/PopupModel/index.jsx
  src/components/RecentDesignCard/index.jsx
  src/containers/Favourite/index.jsx
  src/containers/ProfileEditor/index.jsx
  src/containers/SettingsContainer/index.jsx
  src/containers/TeamContainer/index.jsx
Labels: gssoc23, 🟥 priority: critical, ⭐ goal: addition, level2
