Repository amanjaiman1/Product_3D, pull requests merged in 2023-07, with the labels that each got.

#432 feat: Created Auto-commit Workflow. ✔
  .github/workflows/auto-commit.yml
Labels: gssoc23, level2

#434 added contact design
  client/src/pages/Contact/Contact.css
  client/src/pages/Contact/Contact.jsx
Labels: gssoc23, 🟨 priority: low, level2

#468 feat(navbar): Re-Designed Navbar
  client/src/containers/Header/Navbar.jsx
Labels: gssoc23, 🟧 priority: high, level3

#458 feat: make testimonials accessible ✨
  client/src/containers/TeamPost/TeamPostCard.jsx
Labels: gssoc23, level1

#480 feat: added token verification with firebase-admin
  admin/.example.env
  admin/config.js
  admin/index.js
  admin/package-lock.json
  admin/package.json
Labels: gssoc23, 🟥 priority: critical, 👨🏻‍🚒 goal: major, level3

#478 feat: handle error with tostify for login/signup
  package-lock.json
  package.json
  src/App.jsx
  src/utils/PrivateRoute.jsx
  src/utils/errorHandler.jsx
  src/utils/toastMaker.jsx
  src/views/auth/Login.jsx
  src/views/auth/SignUp.jsx
Labels: gssoc23, ⚒️ goal: fix, level3

#486 Added Favicon
  index.html
  public/icons8-shirt-58.png
Labels: gssoc23, ⭐ goal: addition, level2

#504 fix(signup): fixed code in signup page
  src/views/auth/SignUp.jsx
Labels: gssoc23, ⚒️ goal: fix, level3

#510 docs(readme): update the readme file and remove extra contents
  CONTRIBUTING.md
  README.md
Labels: gssoc23, level3

#518 feat: customizer title and go back functionality
  package.json
  src/App.jsx
  src/components/CustomizerTitle/index.jsx
  src/containers/Customizer/index.jsx
Labels: gssoc23, ⭐ goal: addition, level3

#519 feat: Store recent design using firebase
  src/components/CustomizerNavBar/index.jsx
  src/components/CustomizerTopbar/index.jsx
  src/components/DialogBox/index.jsx
  src/components/RecentDesignCard/index.jsx
  src/containers/RecentDesigns/index.jsx
Labels: gssoc23, ⭐ goal: addition, 👨🏻‍🚒 goal: major, level3

#524 refactor: profile update functionality with firebase
  src/containers/ProfileContainer/index.jsx
  src/containers/ProfileEditor/index.jsx
Labels: gssoc23, 🟧 priority: high, ⭐ goal: addition, level3

#525 fix(guidebookcards): made card responsvie
  src/pages/Guidebook/guidebook.jsx
Labels: 🟧 priority: high, ⚒️ goal: fix, level1

#540 docs: correct discord link in README.md
  README.md
Labels: gssoc23, level1, kind/documentation

#553 feat: logoChanged
  src/assets/image/newLogo.png
  src/assets/index.js
  src/containers/Header/Navbar.jsx
Labels: gssoc23, 🟥 priority: critical, level2

#557 feat: background image with hero section
  public/frame.png
  src/App.jsx
  src/assets/image/male.png
  src/components/Button/index.jsx
  src/containers/Header/Navbar.jsx
  src/containers/Hero/homeUI.css
  src/containers/Hero/index.jsx
  src/index.css
  src/layout/HomeLayout.jsx
  src/views/app/Home/index.jsx
Labels: gssoc23, 🟧 priority: high, level3

#558 [FEAT]: footer Designed
  src/App.jsx
  src/containers/Footer/index.js
  src/containers/Footer/index.jsx
  src/containers/Hero/index.jsx
Labels: gssoc23, 👨🏻‍🚒 goal: major, level3

#564 feat: setting page for customizer
  src/App.jsx
  src/components/CustomizerColor/index.jsx
  src/components/CustomizerLogo/index.jsx
  src/components/CustomizerSidebar/index.jsx
  src/components/CustomizerText/index.jsx
  src/components/CustomizerTopbar/index.jsx
  src/containers/SettingsContainer/index.jsx
  src/views/app/Settings/index.jsx
Labels: gssoc23, 🟧 priority: high, level3

#567 [FEAT]: Designing the text area of hero section
  src/containers/Hero/index.jsx
Labels: gssoc23, 🟧 priority: high, level2

#572 Removed margin and padding at home layout.
  src/layout/HomeLayout.jsx
Labels: gssoc23, ⚒️ goal: fix, level2

#578 style: news letter fix
  src/containers/NewsLetter/index.jsx
  src/views/app/Home/index.jsx
Labels: gssoc23, level1

#579 [FEAT]: Added Feature Card
  src/components/FeatureCard/index.jsx
  src/containers/HightLights/index.js
  src/containers/HightLights/index.jsx
  src/index.css
  src/views/app/Home/index.jsx
Labels: gssoc23, 🟧 priority: high, ⭐ goal: addition, level3
